### ISSUE TITLE
libtiff install fails

### ISSUE THREAD

**Issue by collinsr** [Kitware/fletch#49] opened 2016-07-25 17:39 UTC
If fletch_ENABLE_libtiff is turned on, the build fails due to what looks like a misconfigured installation variable:

```
[...]
[ 98%] Built target tiff-grayscale
[100%] Built target iptcutil
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:39 (file):
  file cannot create directory: /lib/pkgconfig.  Maybe need administrative
  privileges.


make[3]: *** [install] Error 1
make[2]: *** [build/src/libtiff-stamp/libtiff-install] Error 2
make[1]: *** [CMakeFiles/libtiff.dir/all] Error 2
make: *** [all] Error 2
```

...note the attempt to write to /lib; it looks like some variable is failing to expand. Replicated on mac (Roddy) and Linux (Linus).

**Comment by hughed2** [comment] 2016-07-25 17:42
I haven't touched master lately, but I've found (and fixed) it on my branch. The problem is fletch/CMake/External_libtiff.cmake:73

Instead of ${vision-tpl_BUILD_INSTALL_PREFIX} it should be ${fletch_BUILD_INSTALL_PREFIX}

**Comment by dstoup** [comment] 2017-12-18 21:19
Appears fix, closing.

**Closed by dstoup** 2017-12-18 21:19 UTC
